-- Create a table for storing manual badges
create table if not exists public.agent_badges (
  id bigint generated by default as identity primary key,
  agent_name text not null,
  badge_id text not null,
  awarded_at timestamp with time zone default timezone('utc'::text, now()) not null,
  awarded_by text default 'admin'
);

-- Create table for report batches (groups of uploads)
create table if not exists public.report_batches (
  id uuid default gen_random_uuid() primary key,
  upload_date timestamp with time zone default timezone('utc'::text, now()) not null,
  batch_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create table for individual agent reports
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  batch_id uuid references public.report_batches(id),
  agent_name text not null,
  chats_count integer default 0,
  avg_chat_time text,
  total_chat_time text,
  last_message_sent text,
  avg_score double precision default 0,
  rating_times integer default 0,
  score_1 integer default 0,
  score_2 integer default 0,
  score_3 integer default 0,
  score_4 integer default 0,
  score_5 integer default 0
);

-- Set up Row Level Security (RLS)
alter table public.agent_badges enable row level security;
alter table public.report_batches enable row level security;
alter table public.reports enable row level security;

-- Allow all access for now (can be restricted later)
create policy "Enable all access for all users" on public.agent_badges
  for all using (true) with check (true);

create policy "Enable all access for all users" on public.report_batches
  for all using (true) with check (true);

create policy "Enable all access for all users" on public.reports
  for all using (true) with check (true);

-- Create table for agent notes (bulk messages)
create table if not exists public.agent_notes (
  id bigint generated by default as identity primary key,
  agent_name text not null,
  note text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  read_at timestamp with time zone,
  agent_reply text
);

-- Enable RLS for agent_notes
alter table public.agent_notes enable row level security;

-- Allow all access for agent_notes
create policy "Enable all access for all users" on public.agent_notes
  for all using (true) with check (true);

-- Create table for agent goals
create table if not exists public.agent_goals (
  id bigint generated by default as identity primary key,
  agent_name text not null,
  metric_type text not null, -- 'score', 'chats', 'time'
  target_value double precision not null,
  current_value double precision default 0,
  status text default 'active', -- 'active', 'completed', 'expired'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  deadline timestamp with time zone
);

-- Enable RLS for agent_goals
alter table public.agent_goals enable row level security;

-- Allow all access for agent_goals
create policy "Enable all access for all users" on public.agent_goals
  for all using (true) with check (true);
